### ISSUE TITLE
مشکل در بیلد

### ISSUE THREAD

**Issue by HrBDev** [ham3da/daryaye-sokhan#3]
.بنظر میرسد چند فایل و یک متد در رپو آپلود نشده اند و برای اجرای پروژه مورد نیاز هستند

![image](https://user-images.githubusercontent.com/25826502/78721725-4ffa6f80-793d-11ea-8391-1ba41e22dcc7.png)
![image](https://user-images.githubusercontent.com/25826502/78721838-8801b280-793d-11ea-96fe-507dd6c929da.png)
![image](https://user-images.githubusercontent.com/25826502/78721901-a36cbd80-793d-11ea-8ec0-f662d32dbdb7.png)

**Comment by ham3da** [comment]
درود بر شما و ممنونم بابت همکاری در پروژه.
 فردا این مورد را بررسی می‌کنم و نتیجه را همینجا خدمت شما اعلام می‌کنم

**Comment by ebraminio** [comment]
<div dir="rtl">
بله من هم همین مشکل رو داشتم، ظاهراً آن دو فایل به صورت لوکال مانده‌اند، کاش یک جوری بدون
google-services.json
هم کار می‌کرد، برنامه عالی است، ممنون که سورسشو گذاشتید، دستتون درد نکنه

**Comment by ham3da** [comment]
<p dir="rtl">
تا چند دقیقه دیگه آپلودشون می کنم. 
فقط نمی دونم اگر
 google-services.json 
رو آپ بکنم از لحاظ امنیتی مشکلی نداره؟
</p>

**Comment by ebraminio** [comment]
<div dir="rtl">
فک کنم نه  نباید آپلود کرد همون که داریدو، یدونه خالیشو بذارید فک کنم اونجا باید ردیف باشه یا اگه خیلی از قابلیت‌هاش استفاده نمی‌کنید از خدماتش کلاً حذف شه

**Comment by ham3da** [comment]
استفاده که میشه به خصوص برای ارسال نوتیفکیشن و آمارگیری کاربران. یه جستجو کنم ببینم چی نوشتن در موردش.

**Comment by ham3da** [comment]
<p dir="rtl">
بررسی کردم در گروه مربوط به فایربیس نوشته بودن که اطلاعات محرمانه‌ای در این فایل وجود نداره و میشه به راحتی از فایل apk هم استخراجش کرد. آپلود شد.
</p>
